config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'articles#index'

  resources :pdfs
  resources :articles

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  searchkick

  def self.sql_search(q)
    if q
      articles = Article.where('lower(text) LIKE lower(?)', "%#{q}%")
    else
      articles = []
    end
    articles
  end
end

app/models/concerns/blob_validator.rb
class BlobValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, values)
    return unless values.attached?

    Array(values).each do |value|
      if options[:size_range].present?
        if options[:size_range].min > value.blob.byte_size
          record.errors.add(attribute, :min_size_error, min_size: ActiveSupport::NumberHelper.number_to_human_size(options[:size_range].min))
        elsif options[:size_range].max < value.blob.byte_size
          record.errors.add(attribute, :max_size_error, max_size: ActiveSupport::NumberHelper.number_to_human_size(options[:size_range].max))
        end
      end

      unless valid_content_type?(value.blob)
        record.errors.add(attribute, :content_type)
      end
    end
  end

  private

  def valid_content_type?(blob)
    return true if options[:content_type].nil?

    case options[:content_type]
    when Regexp
      options[:content_type].match?(blob.content_type)
    when Array
      options[:content_type].include?(blob.content_type)
    when Symbol
      blob.public_send("#{options[:content_type]}?")
    else
      options[:content_type] == blob.content_type
    end
  end
end

app/models/pdf.rb
class Pdf < ApplicationRecord
  enum status: [:uploaded, :being_processed, :extracted, :error]

  has_one_attached :file

  after_create :set_status
  after_commit :extract_text_callback

  validates :file, presence: true, blob: { content_type: 'application/pdf' }
  validates :title, presence: true

  #TODO: Refactor into a dedicated search module
  def self.search(q)
    if q
      pdfs = Pdf.where('lower(text) LIKE lower(?)', "%#{q}%")
    else
      pdfs = []
    end
    pdfs
  end

  def get_text_samples(q)
    words = self.text.split(' ')

    begin
      idx = find_occurrences_indexes(q, words)

      start_idx = idx.map { |i| find_sentence_begining(words, i) }

      samples = idx.map do |i|
        start_idx.map do |s_i|
          extract_sentences(words, s_i, i)
        end
      end

    rescue
      ['Unknown error, my script sucks ¯\_(ツ)_/¯']
    end

    samples.flatten.uniq
  end

  def find_occurrences_indexes(q, words)
    words.each_index.select { |i| /#{q}/.match(words[i]) }
  end

  def find_sentence_begining(words, i)
    while true
      return i + 1  if /.*[\.\!\?]$/.match words[i]
      i -= 1
    end
  end

  def extract_sentences(words, start_idx, idx)
    words[start_idx..(idx + 100)].join(' ')
  end
  #####################
  



  def set_status
    self.update!(status: :uploaded) if self.file.present?
  end

  def extract_text_callback
    ExtractTextFromPdfWorker.perform_async(self.id, attachment_local_path)
  end

  def attachment_local_path
    ActiveStorage::Blob.service.send(:path_for, self.file.key)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @q = params.fetch(:search) if params.has_key?(:search)
    if @q
      @articles = Article.search(@q, fields: ['url', 'text^4', 'name'])
      @count = @articles.count
    else
      @articles = []
    end
    #@articles = Article.sql_search(params[:search])
    #@count = @articles.count
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:url, :text, :search)
  end
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
  before_action :set_pdf, only: [:show, :edit, :update, :destroy]

  # GET /pdfs
  # GET /pdfs.json
  def index
    #TODO: Refactor, this is fragile & dangerous code ATM
    @pdfs = Pdf.search(params[:search])
    @text_sample = @pdfs.map { |pdf| pdf.get_text_samples(params[:search]) } if params[:search]
    @results = @pdfs.zip(@text_sample) if params[:search]
    @results ||= @pdfs
    @count = @pdfs.count
  end

  # GET /pdfs/1
  # GET /pdfs/1.json
  def show
  end

  # GET /pdfs/new
  def new
    @pdf = Pdf.new
  end

  # GET /pdfs/1/edit
  def edit
  end

  # POST /pdfs
  # POST /pdfs.json
  def create
    @pdf = Pdf.new(pdf_params)

    respond_to do |format|
      if @pdf.save
        format.html { redirect_to @pdf, notice: 'Pdf was successfully created.' }
        format.json { render :show, status: :created, location: @pdf }
      else
        format.html { render :new }
        format.json { render json: @pdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pdfs/1
  # PATCH/PUT /pdfs/1.json
  def update
    respond_to do |format|
      if @pdf.update(pdf_params)
        format.html { redirect_to @pdf, notice: 'Pdf was successfully updated.' }
        format.json { render :show, status: :ok, location: @pdf }
      else
        format.html { render :edit }
        format.json { render json: @pdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pdfs/1
  # DELETE /pdfs/1.json
  def destroy
    @pdf.destroy
    respond_to do |format|
      format.html { redirect_to pdfs_url, notice: 'Pdf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pdf
      @pdf = Pdf.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pdf_params
      params.require(:pdf).permit(:title, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<div class='container'>
  <div class='alert alert-info' role='alert'>
    Nouveau moteur de recherche: plus tolérant & plus rapide :)
  </div>

  <%= form_tag(articles_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search], class: 'input-block-level') %>
    <%= submit_tag ('Search'), class: 'btn btn-outline-primary' %>
  <% end %>
  <%= pluralize(@count, 'result') %>
  <br>

  <% @articles.each do |article| %>
    <div class='card'>
      <div class='card-body'>
      <h5 class='card-title'><%= link_to(article.name, article.url) %></h5>
      <p class='card-text'><%= highlight(article.text, params[:search]) %></p>
      <%= link_to('Website', article.url, class: 'btn btn-outline-secondary', target: :_blank) %>
      </div>
    </div>
    <br>
  <% end %>

</div>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @article.url %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Home', root_path, class: 'navbar-brand' %>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to 'Global', articles_path, class: "nav-item nav-link #{'active' if current_page?(articles_path)}" %>
      <%= link_to 'Articles', articles_path, class: "nav-item nav-link #{'active' if current_page?(articles_path)}" %>
      <%= link_to 'PDF', pdfs_path, class: "nav-item nav-link #{'active' if current_page?(articles_path)}" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PavillonArsenalSe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style> body { margin-top: 0px; }</style>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pdfs/_form.html.erb
<%= form_with(model: pdf, local: true) do |form| %>
  <% if pdf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pdf.errors.count, "error") %> prohibited this pdf from being saved:</h2>

      <ul>
        <% pdf.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pdfs/edit.html.erb
<h1>Editing Pdf</h1>

<%= render 'form', pdf: @pdf %>

<%= link_to 'Show', @pdf %> |
<%= link_to 'Back', pdfs_path %>

app/views/pdfs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pdfs</h1>


<div class='container'>
  <div class='alert alert-danger' role='alert'>
    Mauvaise nouvelle: pas d'upload de PDF tant que j'ai pas de CB... J'me sers de logiciels (Redis & Sidekiq), et Heroku - la plateforme qui heberge l'application - requière mes infos bancaires même pour les offres gratuites (salauds). La bonne nouvelle c'est qu'un ami à téléchargé l'archive, du coup dès que j'le vois y'aura plus besoin que tu upload les pdf 1 par 1 (mais si tu dois en ajouter au fil du temps, c'est pratique quand même)
  </div>

  <div class='alert alert-success' role='alert'>
    J'adore les alertes !!!
  </div>

  <div class='alert alert-warning' role='alert'>
    <strike> Une fois que le PDF est upload, ça extrait le texte en arrière plan. Vas y molo, upload pas trop de PDF d'un coup, ça risque de tout casser. Si tu vois que l'application répond plus, c'est que c'est cassé ¯\_(ツ)_/¯</strike>
  </div>

  <div class='row mt-2 mb-5'>
    <%= link_to 'Upload a new PDF', new_pdf_path, class: 'btn btn-outline-success btn-lg btn-block' %>
  </div>

  <div class='alert alert-danger my-2' role='alert'>
    <strike>
    Pour le moment: les caractères spéciaux (accents typiquement) sont pas reconnus (remplacés par des points d'intérogation). 
    Si tu fais une recherche trop large, ça va graaaaaaave mouliner ! 
    Aussi, j'arrive pas tout le temps à extraire un échantillon de texte, c'est le prochain chantier ! </strike></div>


  <div class='row mx-auto mt-2'>
    <%= form_tag(pdfs_path, method: :get) do %>
      <%= text_field_tag(:search, params[:search], class: 'input-block-level') %>
      <%= submit_tag 'Search',class: 'btn btn-outline-primary' %>
    <% end %>
  </div>
  <div class='row ml-2'>
    <%= pluralize(@count, 'result') %>
  </div>

  <div class='container ml-2'>
  <% @results.each do |pdf, text_samples| %>
    <div class='card my-2'>
      <div class='card-body'>
        <h5 class='card-title'><%= link_to(pdf.title, pdf.file) %></h5>
        <% text_samples.each do |sample| %>
          <p class='card-text'><%= sample %></p>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/pdfs/new.html.erb
<h1>New Pdf</h1>

<%= render 'form', pdf: @pdf %>

<%= link_to 'Back', pdfs_path %>

app/views/pdfs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pdf.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @pdf.text %>
</p>

<p>
  <strong>File:</strong>
  <%= link_to @pdf.file.filename, @pdf.file if @pdf.file.attached? %>
</p>

<%= link_to 'Edit', edit_pdf_path(@pdf) %> |
<%= link_to 'Back', pdfs_path %>